#!/bin/bash

while getopts g: flag; do
  case "${flag}" in
  g) GO_VER=${OPTARG} ;;
  *) echo "WARN: unknown parameter: ${OPTARG}" ;;
  esac
done

source <(curl -s https://raw.githubusercontent.com/itrocket-team/testnet_guides/main/utils/common.sh)

printGreen "1. Updating packages..." && sleep 1
sudo apt update

printGreen "2. installing dependencies..." && sleep 1
sudo apt install curl git wget htop tmux build-essential jq make lz4 gcc unzip -y

printGreen "3. Installing go..." && sleep 1
cd $HOME
! [ -x "$(command -v go)" ] && {
VER="${GO_VER}"
wget "https://golang.org/dl/go$VER.linux-amd64.tar.gz"
sudo rm -rf /usr/local/go
sudo tar -C /usr/local -xzf "go$VER.linux-amd64.tar.gz"
rm "go$VER.linux-amd64.tar.gz"
[ ! -f ~/.bash_profile ] && touch ~/.bash_profile
echo "export PATH=$PATH:/usr/local/go/bin:~/go/bin" >> ~/.bash_profile
source ~/.bash_profile
}
[ ! -d ~/go/bin ] && mkdir -p ~/go/bin

echo $(go version) && sleep 1
